// Generated by https://quicktype.io

export interface ActividadesFetch {
	ok: boolean;
	data: Actividad[];
	error: null;
}

export interface Actividad {
	idActividad: number;
	idArea: number;
	nro: number;
	desc: string;
	listaProgramasSIPPE: number[];
	listaObjetivos: number[];
	listaRelaciones: number[];
	idUsuario: null;
	fechaDesde: null | string;
	fechaHasta: null | string;
	motivoCancel: null;
	listaMetas: ListaMeta[];
	listaUbicaciones: any[];
	listaInstituciones: ListaInstitucione[];
	listaFechasPuntuales: any[];
	listaEnlaces: ListaEnlace[];
}

export interface ListaEnlace {
	idEnlace: number;
	desc: string;
	link: string;
	idActividad: number;
	createdAt: string;
	updatedAt: string;
	deletedAt: null;
}

export interface ListaInstitucione {
	idInstitucion: number;
	nom: string;
	ubicacion: string;
}

export interface ListaMeta {
	idMeta: number;
	descripcion: string;
	resultado: string;
	observaciones: string;
}
