import { AreaProps } from './AppProps';
export interface navLinkProps {
	title: string;
	index: string;
	SubNav?: navLinkProps[] | null;
}

// Generated by https://quicktype.io

export interface FechProgramasProps {
	ok: boolean;
	data: ProgramaProps[];
	error: null;
}

export interface ProgramaProps {
	idPrograma: number;
	nom: string;
	listaAreas: AreaProps[];
}

export interface AreaProps {
	idArea: number;
	nom: string;
}

// Generated by https://quicktype.io

export interface ActividadesFetch {
	ok: boolean;
	data: Data;
	error: null;
}

export interface Data {
	idActividad: number;
	idArea: number;
	nro: number;
	desc: string;
	listaProgramasSIPPE: number[];
	listaObjetivos: number[];
	listaRelaciones: number[];
	idUsuario: null;
	fechaDesde: string;
	fechaHasta: string;
	motivoCancel: null;
	listaMetas: ListaMeta[];
	listaUbicaciones: any[];
	listaInstituciones: ListaInstitucione[];
	listaFechasPuntuales: ListaFechasPuntuale[];
	listaEnlaces: ListaEnlace[];
}

export interface ListaEnlace {
	idEnlace: number;
	link: string;
	desc: string;
}

export interface ListaFechasPuntuale {
	idFecha: number;
	fecha: string;
}

export interface ListaInstitucione {
	idInstitucion: number;
	nom: string;
	ubicacion: string;
}

export interface ListaMeta {
	idMeta: number;
	descripcion: string;
	resultado: string;
	observaciones: null;
	valoracion: number;
}
