export interface LoginResponse {
	ok: boolean;
	data: Data;
	error: null | string;
}

export interface Data {
	idUsuario: string;
	email: string;
	ape: string;
	nom: string;
	token: string;
	categorias: Categoria[];
}

export interface Categoria {
	categoria: string;
	permiso: string;
}

// Generated by https://quicktype.io

export interface RegisterProps {
	dni:               string;
	ape:               string;
	nom:               string;
	idUnidadAcademica: number;
	email:             string;
	pass:              string;
	confirmPass:       string;
}
