// Generated by https://quicktype.io

export interface BasesFetch {
  ok:   boolean;
  data: Data;
}

export interface Data {
  lAreas:              LArea[];
  listaObjetivos:      ListaObjetivo[];
  listaProgramasSIPPE: any[];
  listaRelaciones:     ListaRelacione[];
  listaValoraciones:   ListaValoracione[];
  unidadesAcademicas:  ListaRelacione[];
}

export interface LArea {
  idRelacion:     number;
  nom:            string;
  idTipoRelacion: number;
}

export interface ListaObjetivo {
  idObjetivo:   number;
  nom:          string;
  detalle:      null | string;
  tipoObjetivo: TipoObjetivo;
}

export interface TipoObjetivo {
  idTipoObj: number;
  nom:       TipoObjetivoNom;
}

export enum TipoObjetivoNom {
  EjeTransversal = "Eje Transversal",
  LíneaInstitucionalEstratégica = "Línea Institucional Estratégica",
  ObjetivoEstratégico = "Objetivo Estratégico",
}

export interface ListaRelacione {
  idRelacion:   number;
  nom:          string;
  tipoRelacion: TipoRelacion;
}

export interface TipoRelacion {
  idTipoRelacion: number;
  nom:            TipoRelacionNom;
}

export enum TipoRelacionNom {
  InternaExtensión = "interna_extensión",
  InternaUnl = "interna_unl",
  UA = "U.A.",
}

export interface ListaValoracione {
  idValoracion: number;
  nom:          string;
}
