// Generated by https://quicktype.io

export interface ResponseProjectsProps {
	ok: boolean;
	data: DataProjectsProps;
	error: null;
}

export interface DataProjectsProps {
	listaProyectosUsuario: ProjectProps[];
}

export interface ProjectProps {
	id: number;
	codigo: string;
	titulo: string;
	fechaCreacion: string;
	responsable: string;
	estado: Estado;
}

export enum Estado {
	Adm = 'ADM',
	NoPert = 'NO_PERT',
	Ok = 'OK',
}

export interface projectHistoryProps {
	id: number;
	desc: string;
	tipoEstado: string;
	fechaCreacion: Date;
}

export interface IntegranteEquipoProps {
	observ: null;
	tieneTarjeta: number;
	lrol: string[];
	dni: string;
	ape: string;
	nom: string;
	titulo: null | string;
	email: null | string;
	dom: null | string;
	tel: null | string;
	categoriaDocente: null;
	categoriaDedicacion: null;
	unidadAcademica: string;
	periodoLectivo: null;
	area: null;
}
